
 export const anime = [
  {
    id: 1,
    title: "Campfire Cooking in another world",
    slug: "campfire-cooking",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753965482/campcook_kx0avb.webp",
    level: "JPLT N5",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 2,
    title: "Mob Psycho",
    slug: "mob-psycho",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753965584/mob_pnwo7i.jpg",
    level: "JPLT N4",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 3,
    title: "Classroom of The Elite",
    slug: "cote-s2",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753965666/cote_zrqcpp.jpg",
    level: "JPLT N5",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 4,
    title: "Spy X Family",
    slug: "spy-x-family",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753965846/spyx2_qraxin.webp",
    level: "JPLT N4",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 5,
    title: "Jojo's bizarre Adventure - Stardust Crusaders",
    slug: "jojo",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753965994/jojo_kvy9zy.webp",
    level: "JPLT N2",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 6,
    title: "Tokyo Revengers",
    slug: "tokyo-revengers",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753966177/tokyorev_oapu20.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 7,
    title: "That Time I Got Reincarnated as a Slime",
    slug: "reincarnte-slime",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753966298/slime_bumbsz.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 8,
    title: "Dan Da Dan",
    slug: "dandadan",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753967575/dandadan_ssewda.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 9,
    title: "School Babysitters",
    slug: "school-babysitters",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753966646/school_wntdm7.webp",
    level: "JPLT N5",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 10,
    title: "I Parry Everything",
    slug: "parry-everything",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753967259/parry_ns34tj.webp",
    level: "JPLT N2",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 11,
    title: "Cheer Boys",
    slug: "cheer-boys",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753966750/chher_zpqoqx.jpg",
    level: "JPLT N5",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 12,
    title: "Ragna Crimson",
    slug: "ragna-crimson",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753967795/ragna_fa7kuy.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 13,
    title: "Zom 100",
    slug: "zom-100",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753967924/zom_o4e5gt.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 14,
    title: "Loner Life In Another World",
    slug: "loner-life",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753968182/loner_fz3bdc.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 15,
    title: "The Seven Deadly Sins",
    slug: "seven-sins",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753968466/seven_hr4fgs.jpg",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 16,
    title: "Re: Zero",
    slug: "re-zero",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753968622/rezero_ls450l.webp",
    level: "JPLT N2",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 17,
    title: "Mob Psycho II",
    slug: "mob-2",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753968884/mob2_hgtxqn.jpg",
    level: "JPLT N2",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 18,
    title: "Jojo's bizarre Adventure - Diamond is Unbreakable",
    slug: "jojo-diamond",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753969065/jojo4_sfkfje.jpg",
    level: "JPLT N2",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 19,
    title: "Ippon Again!",
    slug: "ippon-again",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753969295/ippon_qg40fg.webp",
    level: "JPLT N4",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 20,
    title: "Black Bullet",
    slug: "black-bullet",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753969495/black_qimwdb.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 21,
    title: "Just Because!",
    slug: "just-because",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753969757/justbecause_k927p2.webp",
    level: "JPLT N4",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 22,
    title: "Sabikui Bisco",
    slug: "sabikui-bisco",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753970042/sabbisco_jbtl4t.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 23,
    title: "Luck and Logic",
    slug: "luck-logic",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753970161/luck_t83w6z.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 24,
    title: "That Time I Got Reincarnated As A Slime - Season 2",
    slug: "slime-s2",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753970305/slimes2_wgpz7z.jpg",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
  {
    id: 25,
    title: "Re: Zero - Season 2",
    slug: "re-zero-2",
    image: "https://res.cloudinary.com/dcdqkzmfi/image/upload/v1753970456/re-2_fjgbpc.webp",
    level: "JPLT N3",
    subtitles: ["Japanese", "English"],
  },
];